### ISSUE TITLE
What's New is outdated

### ISSUE THREAD

**Issue by vstinner** [python-cffi/release-doc#1]
Hi,

https://cffi.readthedocs.io/en/latest/whatsnew.html shows v1.14.2 as the latest version, whereas https://pypi.org/project/cffi/ says 1.14.4 (and 1.14.2 been released in August 2020).

Is https://cffi.readthedocs.io/ outdated? The footer says "Revision b737fc87" : https://github.com/python-cffi/release-doc/commit/b737fc87 was pushed 9 days ago.

See https://github.com/python-cffi/release-doc/blob/master/doc/source/whatsnew.rst

**Comment by arigo** [comment]
Done, added "documentation" for the two missing revisions.

**Comment by vstinner** [comment]
Thank you!
